/*
     This module creates IMDG unit on data obtained from cxml file generated by MACS3 software
*/
#ifndef IMDGUNIT_H
#define IMDGUNIT_H

#include <QVector>
#include <QDebug>
#include <QList>
#include "xmltag.h"
#include "container.h"


class IMDGunit{
public:

    IMDGunit();
    IMDGunit(QList<QString> imdgDataReceived);
    IMDGunit(const IMDGunit &imdgUnitCopy);
    ~IMDGunit();




    IMDGunit &operator=(const IMDGunit &imdgUnit);

    QString getUnitValueOnTag(const TAGNAME tag) const;
    QString getDagoID() const;
    QString getDagoEID() const;
    QString getDagoUNNo() const;
    QList<QString> getImdgUnitData() const;
    QString getDataToString()const;
    int getIndexOnTag(TAGNAME tag) const;
    int getListIndexOnTag(TAGNAME tag) const;
    int getItemsQty() const ;
    QString getValueOnIndex(int index)const;




    int  setValueOnIndex(int index, QString value);
    void setData(QList<QString> data);
    void replaceImdgUnit(QList<QString> data);
    void removeAllItems();

    bool isImdgUnitEmpty() const;
    bool isWeightTagExists() const;
    int insertValueIntoUnit(QString unitFullLine, TAGNAME whereTagIs);
    int inserValueIntoUnit(QString untiFullLine);
    bool addWeightToIMDGunit(QVector<IMDGunit> &newUnits, Container &dataToInsert,
                                        int unnoCounter, bool isNextUnitDifferent);


    QString packingGroupToNumber(QString packingGroup);


private:

    QList<QString>      imdgUnitData;
    XmlTag              xmlTags;












};

#endif // IMDGUNIT_H

